version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - app-network

  # Auth Service
  auth-service:
    build:
      context: ./Auth Service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27018/auth?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - app-network

  # Profile Service
  profile-service:
    build:
      context: ./Profile Service
      dockerfile: Dockerfile
    container_name: profile-service
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27018/profiles?authSource=admin
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - app-network

  # Blog Service
  blog-service:
    build:
      context: ./Blog Service
      dockerfile: Dockerfile
    container_name: blog-service
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27018/blogs?authSource=admin
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - app-network

  # Comment Service
  comment-service:
    build:
      context: ./Comment Service
      dockerfile: Dockerfile
    container_name: comment-service
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27018/comments?authSource=admin
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
