name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-services:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ 'i228762' }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE"
        for service in "Auth Service" "Profile Service" "Blog Service" "Comment Service"; do
          cd "$service" && npm ci && cd ..
          echo "dependencies for $service installed"
        done
    
    - name: Install test dependencies
      run: echo "test dependencies installed"
    
    - name: Start services
      run: docker-compose up -d 
      env:
        MONGO_ROOT_USER: ${{ 'i228762' }}
        MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    

    
    - name: Run API tests
      run: echo "API tests"

  