name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-services:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ 'i228762' }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE"
        for service in "Auth Service" "Profile Service" "Blog Service" "Comment Service"; do
          cd "$service" && npm ci && cd ..
          echo "dependencies for $service installed"
        done
      run: apt-get install docker-compose
    
    - name: Install test dependencies
      run: echo "test dependencies installed"
    
    - name: Start services
      run: |
        docker-compose up -d
      env:
        MONGO_ROOT_USER: ${{ 'i228762' }}
        MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    - name: Wait for services
      run: |
        apt-get update && apt-get install -y curl
    
    - name: Run API tests
      run: echo "API tests"

  